services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pa55w0rd2019
            - MSSQL_PID=Express
        expose:
            - 1433
        ports:
            - 1433:1433

    redis:
        image: redis:latest
        container_name: redis
        expose:
            - 6379
        ports:
            - 6379:6379
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: rediscommander
        environment:
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=root
            - HTTP_PASSWORD=secret
        expose:
            - 8081
        ports:
            - 8081:8081

volumes:
    redis-data:
