services:
    sqlserver:
        extends:
            file: common-services.yml
            service: sqlserver

    redis:
        extends:
            file: common-services.yml
            service: redis

    webapi:
        build:
            context: .
            dockerfile: src/Keyshoot.Api/Dockerfile
        container_name: webapi
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=https://+:5001;http://+:5000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=PawCio97
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
        expose:
            - 5000
            - 5001
        ports:
            - 5000:5000
            - 5001:5001
        depends_on:
            - sqlserver
            - redis
            - identity
        volumes:
            - ./ssl/:/https:ro

    identity:
        build:
            context: .
            dockerfile: src/Keyshoot.Identity/Dockerfile
        container_name: identity
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=https://+:7001;http://+:7000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=PawCio97
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
        expose:
            - 7000
            - 7001
        ports:
            - 7000:7000
            - 7001:7001
        depends_on:
            - sqlserver
        volumes:
            - ./ssl:/https:ro

    web:
        build:
            context: .
            dockerfile: src/Keyshoot.Web/Dockerfile
        container_name: web
        restart: always
        ports:
            - 4200:4200
        depends_on:
            - webapi
            - identity
        command: ng serve --host 0.0.0.0
        
volumes:
    redis-data:
